samsmithnz/AzurePipelinesToGitHubActionsConverter

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRootBase.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Trigger.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/GitHubActionsRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Trigger.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/TriggerDetail.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ObjectCreationTests.cs, README.md
=> Addressing #7: trigger support

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRootBase.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Trigger.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs
Addresses Issue #8 : adding PR support
=> Added initial PR support

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Strategy.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Strategy.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTest.cs
=> Implemented basic strategy matrix

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Global.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TestUtility.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TriggerTests.cs
=> Continuing to add functionality to steps and some bug fixes

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTest.cs, README.md
=> Added more unit tests to test more possibilities

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/IncludeExclude.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Pool.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Stage.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Step.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Strategy.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Trigger.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/GitHubActionsRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Step.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Strategy.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Trigger.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/TriggerDetail.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Global.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/GlobalTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/LargePipelineTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ObjectCreationTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TestUtility.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TriggerTests.cs
=> Massive cleanup of unused using statements

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Stage.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Job.cs
=> Created basic conditions conversion

.github/workflows/CI.yml, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, README.md
Publish the core module to nuget for consumption for others.
=> Publishing tweak

.github/workflows/CI.yml, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.ConsoleApp/Program.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Step.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubConversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/LargePipelineTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTest.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TriggerTests.cs
- Version promotion to 0.2
- breaking changes aplenty as the main conversion function now returns more than a yaml string, it returns an object that contains the yaml string and a list of messages that can be used to track errors and recommendations
=> Adding a messaging system to handle errors better

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.ConsoleApp/AzurePipelinesToGitHubActionsConverter.ConsoleApp.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Pipelines.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Global.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConvertTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ObjectCreationTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/UtilityTests.cs
Refactoring the conversion slightly to be more standard, increasing version to 0.8.0, as there are a few breaking changes.
=> More enhancements part10

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Variables.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ObjectCreationTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/VariableTests.cs, README.md
Adding complex variables, from issue #62
=> Initial commit for complex variables

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/AzurePipelinesRoot.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Job.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/TemplateTests.cs
=> Code to try and handle templates and parameters better

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesStepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/ConditionsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConditionTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
=> Fix to handle basic system environment variables

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/PipelineProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/AzurePipelinesSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/GitHubActionsSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/VariableTests.cs
=> Resolves variable insertation exception

.github/workflows/CI.yml, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/GitHubActionsSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/LargePipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/UtilityTests.cs, README.md
Addresses:
- #88 Null reference error
- #87 Multi-line pipe missing
- #42 extra lines in some situations
- #43 Differences between windows and Linux build
=> Enhancements part12

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/PipelineProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/LargePipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, README.md
Fix to readme and msbuild task, as well as refactoring to improve the process to insert extra steps as needed
Also addresses 
- #82, Ant support
- #92, Python support
=> Upgrades to Azure and Java tasks, as well as fixes to the MSBuild task

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelines/Step.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/GitHubActions/Step.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/ConditionTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/PipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
Addresses:
- #93 
- #103 
- #84
- #85
=> Fixed the VSTest and improved tests

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
=> replaced @master with @v2 on upload action to follow best practices

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
=> Added support for the Npm@1 task

AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/PipelineProcessing.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/GenericObjectSerialization.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.Tests/PoolTests.cs, AzurePipelinesToGitHubActionsConverter/AzurePipelinesToGitHubActionsConverter.sln
Exposed by #128, but this doesn't fix the issues exposed there, just returns the errors again.
=> Fixes regression where errors were no longer being returned to the call stack root

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/PipelineProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/AzurePipelinesSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/PoolTests.cs
- Fixing a regression where only one job is returned
- Adding back Alex's deserialization methods now that I have a error handling solution
- Corrected the naming of jobs when certain jobs with stages are passed in
- Created some new tests to regression these weird scenarios I hadn't thought of before.
=> Continuing to chip away at a few issues found in testing. 

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/VariableTests.cs
=> Conditional variables

src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/PipelineProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/Serialization/AzurePipelinesSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion/StepsProcessing.cs
- Added a constructor override to suppress Console.WriteLine logging
- Fixed bug with badly configured DotNetCLI input task
- Handled complex variable group issue.
- added misc Debug.WriteLine inside catch statements to highlight a future fix potential
=> misc fixes/tweaks

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Stage.cs, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StagesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/GitHubActionsSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/PoolTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
Fixing some bugs for @maximivanov
=> Fixed stage/job Pool bug and added support for Cache Task

README.md, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConditionsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/SystemVariableProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/GitHubActionsSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ConditionTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
This is our current table of how we are translating [Azure DevOps](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) system variables, to [GitHub Environment variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables).
| Azure Pipelines | GitHub Actions |
| -- | -- |
| Build.ArtifactStagingDirectory | github.workspace | 
| Build.BuildId | github.run_id |
| Build.BuildNumber | github.run_number |
| Build.SourceBranch | github.ref |
| Build.Repository.Name | github.repository |
| Build.SourcesDirectory | github.workspace |
| Build.StagingDirectory | github.workspace |
| System.DefaultWorkingDirectory | github.workspace |
| Agent.OS | runner.os|
=> Updating system variables

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/FolderOfYAMLFilesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
=> Added AzurePowershell, AzureCLI, and expanded MSBuild support

.github/workflows/CI.yml, GitVersion.yml, README.md
=> Setup releases using GitVersion

.github/workflows/CI.yml, src/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
fixes #179 
Also some CI/CD pipeline hardening to handle multiple/manual runs when the source code hasn't changed.
=> Added basic github release task

.github/workflows/CI.yml, README.md, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/AzurePipelinesToGitHubActionsConverter.Tests.csproj
=> Adding code coverage badge

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConversionUtility.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/PipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
- fixes #138 
- fixes #191 (duplicate task)
=> Added DownloadPipelineArtifact@2 processing and improved DownloadBuildArtifacts

.github/workflows/CI.yml, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Trigger.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/TriggerProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ContainerTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/JobsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/TriggerTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/VariableTests.cs, src/AzurePipelinesToGitHubActionsConverter.sln
- Fixes #202 (Bash@3 task)
- Fixes #203 (PowerShell@1 task)
- Fixes #204 (Extract Files task)
- Added test to confirm edge case when there is a trigger for both push and a schedule  
- Fixed logic bug in environments that caused them to not be processed corrected when there were no tags
=> Added support for new tasks

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Canary.cs, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/On.cs, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Rolling.cs, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Strategy.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConditionsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/JobProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StagesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StrategyProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/TriggerProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ConditionTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ExampleTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTests.cs
- fixes #183 (Hugo)
- fixes #215 (Canary and Rolling Strategy crashes)
=> Added support for more tasks

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/JobProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/JSONSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/JobsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTests.cs
- Added fixes to handle dotnet nuget push
- fixes #104 (CMake task)
- fixes #217 (BatchScript task)
- fixed edge case bug with strategy introduced in the last pull request that didn't add tasks for a matrix
- Added more properties to checkout task
- fixes #218 (multiple checkouts)
=> More fixes to steps to improve quality

.github/workflows/CI.yml, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConditionsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConversionUtility.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StagesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StrategyProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/TriggerProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/GitHubActionsSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/PipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsDockerTests.cs
- fixed #224 (ARCHIVEFILES@1)
- Improved test coverage
- Optimized pipeline performance, to not upload the (identical) nuget package and coverall results multiple times
=> Fixes to various tasks and improving tests

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
- fixes #229 (AzurePowerShell@5)
- fixes #230 (ShellScript@2/Bash)
=> Added support for alternative scripting tasks 

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
- fixes #234 (NuGetToolInstaller)
- fixes #233 (AzureKeyVault)
=> Added new tasks

README.md, src/.editorconfig, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConditionsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConversionUtility.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StrategyProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/SystemVariableProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ConditionTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/FolderOfYAMLFilesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StrategyTests.cs, src/AzurePipelinesToGitHubActionsConverter.sln
- fixes #246 (conditions bug)
- Added editor config file to define basic coding standards
- Upgrades to nuget setup to upgrade to official nuget tasks
- Upgrade to msbuild setup to use latest (1.0.2) version
=> Added editor config file to define basic coding standards

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Repositories.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/ResourcesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
Azure Repos and Bitbucket tests still to come.
- Fixes #8 . Finally.
=> Added support for GitHub repository conversions

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs
=> Added InnerPowerShell@1 support

src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
Doesn't solve anything - but chips away a little at #109
=> Added JUNIT sample, need more solutions

src/.editorconfig, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTests.cs
=> Added fix to dotnet task when there are multiple projects

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Job.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConversionUtility.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/JobProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StagesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StagesTests.cs
effectively to make them flow downstream when converted to jobs in GitHub Actions
fixes #200
=> Added fix when there are stage dependsOn

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs
=> Added support for DotNetCoreCLI@1

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsMiscTests.cs
=> Added new UseNode@1 Task

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsMiscTests.cs
=> Added additional GitVersion items and GitVersion setup

src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsModel/Trigger.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/GitHubActionsSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/TriggerTests.cs
=> Added workflow dispatch as an optional parameter to the public api

.github/workflows/CI.yml
Previous version introduced new bugs :(
=> Reverted CI/CD back to previous version for push to NuGet.

.github/workflows/CI.yml
attempt to fix https://github.com/samsmithnz/AzurePipelinesToGitHubActionsConverter/issues/297
=> change dotnet nuget push source

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Conversion.cs, src/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsModel/GitHubActionsRoot.cs, src/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsModel/Job.cs, src/AzurePipelinesToGitHubActionsConverter.Core/GitHubActionsModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Core/GlobalSuppressions.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConditionsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/ConversionUtility.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/GeneralProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/JobProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StagesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StrategyProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/VariablesProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/GitHubActionsSerialization.cs, src/AzurePipelinesToGitHubActionsConverter.Core/Serialization/JSONSerialization.cs
Primary goals are to
- simply boolean comparisons. e.g. [expression] == true will become [expression], and [expression] == false will become ![expression]
- fixed short circuits to always be && or || instead of & or |
- Added stringbuilder in a few places to replace string concat - should improve performance.
=> Resolving SonarCloud code smells - round 1

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsAzureTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsMiscTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsTerraformTests.cs
- fixes a couple of null reference exceptions that I came across whilst bulk testing pipeline conversion w/yamlizr
=> handle null references

.github/workflows/CI.yml, .github/workflows/codeql-analysis.yml, GitVersion.yml, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Tests/AzurePipelinesToGitHubActionsConverter.Tests.csproj
=> Upgraded tests to .NET 6 and packages to latest versions. 

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/OctopusDeployTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/OctopusTests.cs
=> Adding octopus conversion

.github/workflows/CI.yml, README.md
- Fixed incorrect status on readme page
- Fixed download artifact task that was not downloading the build after the upgrade to @v2.0
=> Fix to build

src/AzurePipelinesToGitHubActionsConverter.Core/PipelinesToActionsConversion/StepsProcessing.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/StepsMiscTests.cs
=> Upgraded github actions tools to 0.9.11

GitVersion.yml
It's time. Finally! This has been ready for some time.
=> Update to v1.0.0

src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesModel/Step.cs, src/AzurePipelinesToGitHubActionsConverter.Tests/CompletePipelineTests.cs
=> Adding missing fetchTags property to step

.github/workflows/CI.yml, .github/workflows/codeql-analysis.yml, GitVersion.yml, src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj, src/AzurePipelinesToGitHubActionsConverter.Tests/AzurePipelinesToGitHubActionsConverter.Tests.csproj
This pull request contains updates to various package versions and dependencies to improve the compatibility and performance of the codebase. The most important changes include updating the .NET version in the CI workflow and updating the `next-version` in `GitVersion.yml`.
Package and dependency updates:
* <a href="diffhunk://#diff-b1dfa576a4a15643c593814e278bb74776ecc2ffbc854510eade6b1f04107561L25-R28">`src/AzurePipelinesToGitHubActionsConverter.Core/AzurePipelinesToGitHubActionsConverter.Core.csproj`</a>: Updated package versions for `GitHubActionsDotNet`, `System.Text.Json`, and `YamlDotNet`.
* <a href="diffhunk://#diff-3ab46ee209a127470fce3c2cf106b1a1dbadbb929a4b5b13656a4bc4ce19c0b8L84-R84">`.github/workflows/CI.yml`</a>: Updated the .NET version from 7.0.x to 8.0.x in the CI …
=> .NET 8 upgrade
